CREATE TABLE sec_user (
  userId            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userName             VARCHAR(75) NOT NULL UNIQUE,
  encryptedPassword VARCHAR(128) NOT NULL,
  enabled           BIT NOT NULL 
);

CREATE TABLE sec_role(
  roleId   BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  roleName VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_role
(
  id     BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId BIGINT NOT NULL,
  roleId BIGINT NOT NULL
);

ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk1 UNIQUE (userId, roleId);

ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk2 FOREIGN KEY (userId)
  REFERENCES sec_user (userId);
 
ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk3 FOREIGN KEY (roleId)
  REFERENCES sec_role (roleId);
  
  
CREATE TABLE COURSE_CATEGORIES (
CATEGORY_ID NUMERIC(4,0),
CATEGORY_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE COURSES (
COURSE_ID NUMERIC(6,0) PRIMARY KEY AUTO_INCREMENT,
COURSE_TITLE VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
INSTRUCTOR VARCHAR(100),
PRICE NUMERIC(8,2),
DURATION NUMERIC(4,1), -- hours
PLATFORM VARCHAR(50),
DESCRIPTION VARCHAR(255),
PRIMARY KEY (COURSE_ID)
);